[package]
name = "openschafkopf_util"
version = "0.1.0"
authors = ["openschafkopf <openschafkopf>"]
edition = "2021"
license-file = "../LICENSE"

[dependencies]
itertools = "0"
# TODO: can we get rid of these?
log = "0"
fern = "0"
dirs = "2"
chrono = "0"
