echo "Testing that every other player has no more than 3 Trumpf"
./target/release/openschafkopf hand-stats --rules "Herz-Wenz von 0" --hand "hz hk ho h8 h7 ga ea sa" --simulate-hands 1000000 --inspect "ctx.trumpf(1)<4&&ctx.trumpf(2)<4&&ctx.trumpf(3)<4"
echo "Testing that every other player has Eichel"
./target/release/openschafkopf hand-stats --rules "Herz-Wenz von 0" --hand "hz hk ho h8 h7 ga ea sa" --simulate-hands 1000000 --inspect "0<ctx.eichel(1)&&0<ctx.eichel(2)&&0<ctx.eichel(3)"
echo "Testing that every other player has Eichel, Gras, Schelln"
./target/release/openschafkopf hand-stats --rules "Herz-Wenz von 0" --hand "hz hk ho h8 h7 ga ea sa" --simulate-hands 1000000 --inspect "0<ctx.eichel(1)&&0<ctx.eichel(2)&&0<ctx.eichel(3)&&0<ctx.gras(1)&&0<ctx.gras(2)&&0<ctx.gras(3)&&0<ctx.schelln(1)&&0<ctx.schelln(2)&&0<ctx.schelln(3)"
echo "Testing that every other player has Eichel, Gras, Schelln and no more than 3 trumpf"
./target/release/openschafkopf hand-stats --rules "Herz-Wenz von 0" --hand "hz hk ho h8 h7 ga ea sa" --simulate-hands 1000000 --inspect "0<ctx.eichel(1)&&0<ctx.eichel(2)&&0<ctx.eichel(3)&&0<ctx.gras(1)&&0<ctx.gras(2)&&0<ctx.gras(3)&&0<ctx.schelln(1)&&0<ctx.schelln(2)&&0<ctx.schelln(3)&&ctx.trumpf(1)<4&&ctx.trumpf(2)<4&&ctx.trumpf(3)<4"
